version: 2.1
aliases:
  - &only-tagged-releases
    tags:
      only: /^\d+\.\d+\.\d+(-[a-z\d\-.]+)?$/
    branches:
      ignore: /.*/
  - &only-untagged
    tags:
      ignore: /.*/
orbs:
  docker: circleci/docker@0.5.20
  environment:
    DOCKER_BUILDKIT: 1
executors:
  node:
    docker:
      - image: circleci/node:13.2
        environment:
          DOCKER_BUILDKIT: 1
jobs:
  test-audit:
    executor: node
    steps:
      - checkout
      - run:
          name: Audit js
          command: cd node && npm run test:audit
  test-format:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: cd node && npm ci
      - run:
          name: Test format
          command: cd node && npm run test:format
  test-lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: cd node && npm ci
      - run:
          name: Test lint
          command: cd node && npm run test:lint
  test-types:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: cd node && npm ci
      - run:
          name: Test types
          command: cd node && npm run test:types
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: Install
          command: cd node && npm ci
      - run:
          name: Test
          command:
            cd node && make test
  build-and-push:
    parameters:
      is-release-tag:
        type: boolean
        default: false
    executor: node
    # NOTE: Generally use the CircleCI docker orb for docker build/push jobs
    #       Not able to use it here yet, because this build requires DOCKER_BUILDKIT
    #       for access to private repos installed by npm etc.
    #       https://blog.lelonek.me/private-dependencies-from-github-in-your-docker-container-92e3b8cbf677
    steps:
      - unless:
          condition: <<parameters.is-release-tag>>
          steps:
            - run:
                name: "set image tag to commit sha"
                command: |
                  echo 'export IMAGE_TAG="$CIRCLE_SHA1"' >> $BASH_ENV
      - when:
          condition: <<parameters.is-release-tag>>
          steps:
            - run:
                name: "override image tag to release tag"
                command: |
                  echo 'export IMAGE_TAG="$CIRCLE_TAG"' >> $BASH_ENV
      - run:
          name: report tag
          command: echo "building tag uscictdocker/opentutor-grading-api:${IMAGE_TAG}..."
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - checkout
      - run:
          name: Docker login
          command: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run:
          name: Docker build
          command: cd node && DOCKER_IMAGE=uscictdocker/opentutor-grading-api:${IMAGE_TAG} make docker-build
      - run:
          name: Docker push
          command: docker push uscictdocker/opentutor-grading-api
workflows:
  test-build-deploy:
    jobs:
      - test-format:
          filters: *only-untagged
      - test-audit:
          filters: *only-untagged
      - test-lint:
          filters: *only-untagged
      - test-types:
          filters: *only-untagged
      - test:
          filters: *only-untagged
      - approve-build-and-push:
          filters: *only-untagged
          type: approval
          requires:
            - test-format
            - test-audit
            - test-lint
            - test-types
            - test
      - build-and-push:
          is-release-tag: false
          filters: *only-untagged
          requires:
            - approve-build-and-push
  test-build-deploy-release:
    jobs:
      - test-format:
          filters: *only-tagged-releases
      - test-audit:
          filters: *only-tagged-releases
      - test-lint:
          filters: *only-tagged-releases
      - test-types:
          filters: *only-tagged-releases
      - test:
          filters: *only-tagged-releases
      - build-and-push:
          is-release-tag: true
          filters: *only-tagged-releases
          requires:
            - test-format
            - test-audit
            - test-lint
            - test-types
            - test


  