name: Publish docker image
on:
  push:
    branches: master
  release:
    type:
      - created
    tags:
      - "[0-9]+.[0-9]+.[0-9]"
      - "[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: docker tag
        required: false
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd node && npm ci
      - name: Run audit test
        run: cd node && npm run test:audit
      - name: Run format test
        run: cd node && npm run test:format
      - name: Run lint test
        run: cd node && npm run test:lint
      - name: Run types test
        run: cd node && npm run test:types
      - name: Run license test
        run: cd node && npm run test:license
      - name: Run tests
        run: cd node && npm run test

  build-and-publish:
    needs: test
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
          fi
          echo ::set-output name=image_tag::${IMAGE_TAG}

      - name: Docker login
        run: docker login -u  ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: cd node && DOCKER_BUILDKIT=1 docker build -t uscictdocker/opentutor-graphql:${{ steps.tag.outputs.image_tag }} .

      - name: Docker push
        run: docker push uscictdocker/opentutor-graphql
